/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author CAAG-SL-LAB8
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jFrame1 = new javax.swing.JFrame();
        btnVender = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuEmpleados = new javax.swing.JMenu();
        itemEmpleadoPerfil = new javax.swing.JMenuItem();
        itemEmpleadoNuevo = new javax.swing.JMenuItem();
        itemEmpleadoBuscar = new javax.swing.JMenuItem();
        itemControlEmpleados = new javax.swing.JMenuItem();
        menuClientes = new javax.swing.JMenu();
        itemBuscarCliente = new javax.swing.JMenuItem();
        itemNuevoCliente = new javax.swing.JMenuItem();
        itemControlCliente = new javax.swing.JMenuItem();
        menuInventario = new javax.swing.JMenu();
        itemNuevoProducto = new javax.swing.JMenuItem();
        itemBuscarProducto = new javax.swing.JMenuItem();
        itemControlInventario = new javax.swing.JMenuItem();
        menuProveedores = new javax.swing.JMenu();
        itemNuevoProveedor = new javax.swing.JMenuItem();
        itemControlProveedor = new javax.swing.JMenuItem();
        reportes = new javax.swing.JMenu();
        reporteTodosEmpleados = new javax.swing.JMenuItem();
        itemAyuda = new javax.swing.JMenu();
        itemEnviarCorreo = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar1.png"))); // NOI18N
        btnVender.setText("¡Vender!");
        getContentPane().add(btnVender, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 26, -1, -1));

        jLabel2.setText("ZAGAL");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 421, -1, -1));

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 48)); // NOI18N
        jLabel1.setText("BoreArt");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(628, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(375, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 450));

        menuEmpleados.setText("Empleados");

        itemEmpleadoPerfil.setText("Perfil");
        menuEmpleados.add(itemEmpleadoPerfil);

        itemEmpleadoNuevo.setText("Nuevo");
        menuEmpleados.add(itemEmpleadoNuevo);

        itemEmpleadoBuscar.setText("Buscar");
        menuEmpleados.add(itemEmpleadoBuscar);

        itemControlEmpleados.setText("Control de Empleados");
        menuEmpleados.add(itemControlEmpleados);

        jMenuBar1.add(menuEmpleados);

        menuClientes.setText("Clientes");

        itemBuscarCliente.setText("Buscar");
        menuClientes.add(itemBuscarCliente);

        itemNuevoCliente.setText("Nuevo");
        menuClientes.add(itemNuevoCliente);

        itemControlCliente.setText("Control Cliente");
        menuClientes.add(itemControlCliente);

        jMenuBar1.add(menuClientes);

        menuInventario.setText("Inventario");

        itemNuevoProducto.setText("Nuevo");
        menuInventario.add(itemNuevoProducto);

        itemBuscarProducto.setText("Buscar");
        menuInventario.add(itemBuscarProducto);

        itemControlInventario.setText("Control Inventario");
        menuInventario.add(itemControlInventario);

        menuProveedores.setText("Proveedores");

        itemNuevoProveedor.setText("Nuevo");
        menuProveedores.add(itemNuevoProveedor);

        itemControlProveedor.setText("Control");
        menuProveedores.add(itemControlProveedor);

        menuInventario.add(menuProveedores);

        jMenuBar1.add(menuInventario);

        reportes.setText("Reportes");

        reporteTodosEmpleados.setText("Menú de Reportes");
        reportes.add(reporteTodosEmpleados);

        jMenuBar1.add(reportes);

        itemAyuda.setText("Ayuda");

        itemEnviarCorreo.setText("Enviar Correo");
        itemAyuda.add(itemEnviarCorreo);

        jMenuBar1.add(itemAyuda);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnVender;
    public javax.swing.JMenu itemAyuda;
    public javax.swing.JMenuItem itemBuscarCliente;
    public javax.swing.JMenuItem itemBuscarProducto;
    public javax.swing.JMenuItem itemControlCliente;
    public javax.swing.JMenuItem itemControlEmpleados;
    public javax.swing.JMenuItem itemControlInventario;
    public javax.swing.JMenuItem itemControlProveedor;
    public javax.swing.JMenuItem itemEmpleadoBuscar;
    public javax.swing.JMenuItem itemEmpleadoNuevo;
    public javax.swing.JMenuItem itemEmpleadoPerfil;
    public javax.swing.JMenuItem itemEnviarCorreo;
    public javax.swing.JMenuItem itemNuevoCliente;
    public javax.swing.JMenuItem itemNuevoProducto;
    public javax.swing.JMenuItem itemNuevoProveedor;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    public javax.swing.JMenu menuClientes;
    public javax.swing.JMenu menuEmpleados;
    public javax.swing.JMenu menuInventario;
    public javax.swing.JMenu menuProveedores;
    public javax.swing.JMenuItem reporteTodosEmpleados;
    public javax.swing.JMenu reportes;
    // End of variables declaration//GEN-END:variables
}
